language: node_js
node_js: 10.16.0
before_install:
  - sh -e /etc/init.d/xvfb start
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
script:
  - if [ "x${CORE_BRANCH}x" != "xx" ] ; then ./node_modules/.bin/publish_yalc_package .downstream_cache/core https://github.com/ui-router/core.git && yalc add @uirouter/core ; fi
  - tsc &&
    yarn test &&
    yarn docs &&
    yarn test:downstream
env:
  matrix:
    - CORE_BRANCH=
    - CORE_BRANCH=master UPSTREAM_PKGS=@uirouter/core
notifications:
  slack:
    on_success: never
    rooms:
      secure: Sm72V4Gep8uDeVy5QeQdKAybwwYXC8bLizvW3hnQ+MI9dJxEKBggBKGPeGAU70Pb93UGcE8c/kQzhh5wsJvC143eUXYXMO8g3sJ3gQImUQ317J6OcIEm4LLTwfVHLNM+2HDGcNrlrwMyFEYB7bhoSyqCCa2XELwCKYgRM2Kz7jlR7WJmcPhz++V1hIAW1yi0h4IxtLbhlF6tu6/PbW3jliMbTiePy1YqcihFvEQLWi9MddqbGP7Sde0qul5wgImZJIWWIuTC6ReeXlvD48uhhdiRSSQlB5egsYLHMUbhocOJKrwSk9vP2DAH4v36d3i0a2ySOQOP75i++XuU/ZfglFet5KAjcn2VYgVZyPXtIiTuc+nTSzuzGUPpPF0A1HNGkgGSzVJLSO1aOfIWgo5i/FxzilwUMmExku3is5Ljqi5+phlWQEaBkPllRVA6kJFGeIQWO6BAT+/XXwJVt+q7XiPCfp3ULgwsFLPzbJnXkn8nSCMcqfoCetGlJsNX+2gV4ZE8svES2yUOaXmnY9at0JFQkl/2MZLJZHpGCvAXtxtR9/vqDAe4sVpM/JwdlWvrie0bjiPMk2CK4AIhcUCFC7voIgnZdIlTgztOKC52tb3ZrjIK+BWfCQhemrce3bSCEPf4ApkAyo9HgE5uNmVm1dUiyS68KIZEvy7HloTCDR0=
sudo: false
git:
  depth: 3
cache:
  directories:
    - node_modules
    - '.downstream_cache'
